// Cached references to every element the renderer drives; throws early if markup drifts.

export const getRequiredElement = <T extends HTMLElement>(id: string): T => {
  const element = document.getElementById(id);
  if (!element) {
    throw new Error(`Missing required element: #${id}`);
  }
  return element as T;
};

export const elements = {
  dropZone: getRequiredElement<HTMLDivElement>('dropZone'),
  fileInput: getRequiredElement<HTMLInputElement>('fileInput'),
  fileInfo: getRequiredElement<HTMLDivElement>('fileInfo'),
  fileName: getRequiredElement<HTMLSpanElement>('fileName'),
  fileDetails: getRequiredElement<HTMLSpanElement>('fileDetails'),
  selectedFileList: getRequiredElement<HTMLUListElement>('selectedFileList'),
  clearSelectedFilesBtn: getRequiredElement<HTMLButtonElement>('clearSelectedFilesBtn'),
  browseFilesBtn: getRequiredElement<HTMLButtonElement>('browseFilesBtn'),
  betaLabel: getRequiredElement<HTMLSpanElement>('betaLabel'),
  presetPanelSection: getRequiredElement<HTMLElement>('presetPanelSection'),
  presetPanelToggle: getRequiredElement<HTMLButtonElement>('presetPanelToggle'),
  presetPanelBody: getRequiredElement<HTMLDivElement>('presetPanelBody'),
  presetPanelSummary: getRequiredElement<HTMLSpanElement>('presetPanelSummary'),
  presetSearch: getRequiredElement<HTMLInputElement>('presetSearch'),
  presetSearchAllCheck: getRequiredElement<HTMLInputElement>('presetSearchAllCheck'),
  presetSearchScopeLabel: getRequiredElement<HTMLLabelElement>('presetSearchScopeLabel'),
  presetCountLabel: getRequiredElement<HTMLSpanElement>('presetCountLabel'),
  presetParentList: getRequiredElement<HTMLDivElement>('presetParentList'),
  presetSelectionPreview: getRequiredElement<HTMLDivElement>('presetSelectionPreview'),
  presetCardList: getRequiredElement<HTMLDivElement>('presetCardList'),
  gpuPanelSection: getRequiredElement<HTMLElement>('gpuPanelSection'),
  gpuPanelToggle: getRequiredElement<HTMLButtonElement>('gpuPanelToggle'),
  gpuPanelSummary: getRequiredElement<HTMLSpanElement>('gpuPanelSummary'),
  gpuPanelBody: getRequiredElement<HTMLDivElement>('gpuPanelBody'),
  refreshGpuCapsBtn: getRequiredElement<HTMLButtonElement>('refreshGpuCapsBtn'),
  gpuModeAuto: getRequiredElement<HTMLInputElement>('gpuModeAuto'),
  gpuModeManual: getRequiredElement<HTMLInputElement>('gpuModeManual'),
  gpuManualRow: getRequiredElement<HTMLDivElement>('gpuManualRow'),
  gpuManualVendorSelect: getRequiredElement<HTMLSelectElement>('gpuManualVendorSelect'),
  gpuCapabilityMatrix: getRequiredElement<HTMLDivElement>('gpuCapabilityMatrix'),
  convertBtn: getRequiredElement<HTMLButtonElement>('convertBtn'),
  cancelBtn: getRequiredElement<HTMLButtonElement>('cancelBtn'),
  progressContainer: getRequiredElement<HTMLDivElement>('progressContainer'),
  progressFill: getRequiredElement<HTMLDivElement>('progressFill'),
  conversionQueue: getRequiredElement<HTMLDivElement>('conversionQueue'),
  conversionQueueList: getRequiredElement<HTMLUListElement>('conversionQueueList'),
  retryFailedQueueBtn: getRequiredElement<HTMLButtonElement>('retryFailedQueueBtn'),
  progressPercent: getRequiredElement<HTMLSpanElement>('progressPercent'),
  progressBatchSummary: getRequiredElement<HTMLSpanElement>('progressBatchSummary'),
  progressTime: getRequiredElement<HTMLSpanElement>('progressTime'),
  progressEta: getRequiredElement<HTMLSpanElement>('progressEta'),
  progressSpeed: getRequiredElement<HTMLSpanElement>('progressSpeed'),
  statusMessage: getRequiredElement<HTMLDivElement>('statusMessage'),
  showInFolderBtn: getRequiredElement<HTMLButtonElement>('showInFolderBtn'),
  settingsBtn: getRequiredElement<HTMLButtonElement>('settingsBtn'),
  supportBtn: getRequiredElement<HTMLButtonElement>('supportBtn'),
  titlebar: getRequiredElement<HTMLElement>('titlebar'),
  windowControls: getRequiredElement<HTMLDivElement>('windowControls'),
  windowMinimizeBtn: getRequiredElement<HTMLButtonElement>('windowMinimizeBtn'),
  windowMaximizeBtn: getRequiredElement<HTMLButtonElement>('windowMaximizeBtn'),
  windowCloseBtn: getRequiredElement<HTMLButtonElement>('windowCloseBtn'),
  settingsModal: getRequiredElement<HTMLDivElement>('settingsModal'),
  settingsGeneralTab: getRequiredElement<HTMLButtonElement>('settingsGeneralTab'),
  settingsAdvancedFormatsTab: getRequiredElement<HTMLButtonElement>('settingsAdvancedFormatsTab'),
  settingsDebugTab: getRequiredElement<HTMLButtonElement>('settingsDebugTab'),
  settingsGeneralPanel: getRequiredElement<HTMLDivElement>('settingsGeneralPanel'),
  settingsAdvancedFormatsPanel: getRequiredElement<HTMLDivElement>('settingsAdvancedFormatsPanel'),
  settingsDebugPanel: getRequiredElement<HTMLDivElement>('settingsDebugPanel'),
  showAllGpuVendorsCheck: getRequiredElement<HTMLInputElement>('showAllGpuVendorsCheck'),
  formatTabGif: getRequiredElement<HTMLButtonElement>('formatTabGif'),
  formatTabAv1: getRequiredElement<HTMLButtonElement>('formatTabAv1'),
  formatTabH264: getRequiredElement<HTMLButtonElement>('formatTabH264'),
  formatTabH265: getRequiredElement<HTMLButtonElement>('formatTabH265'),
  formatTabAvi: getRequiredElement<HTMLButtonElement>('formatTabAvi'),
  formatPanelGif: getRequiredElement<HTMLDivElement>('formatPanelGif'),
  formatPanelAv1: getRequiredElement<HTMLDivElement>('formatPanelAv1'),
  formatPanelH264: getRequiredElement<HTMLDivElement>('formatPanelH264'),
  formatPanelH265: getRequiredElement<HTMLDivElement>('formatPanelH265'),
  formatPanelAvi: getRequiredElement<HTMLDivElement>('formatPanelAvi'),
  resetGifDefaultsBtn: getRequiredElement<HTMLButtonElement>('resetGifDefaultsBtn'),
  resetAv1DefaultsBtn: getRequiredElement<HTMLButtonElement>('resetAv1DefaultsBtn'),
  resetH264DefaultsBtn: getRequiredElement<HTMLButtonElement>('resetH264DefaultsBtn'),
  resetH265DefaultsBtn: getRequiredElement<HTMLButtonElement>('resetH265DefaultsBtn'),
  resetAviDefaultsBtn: getRequiredElement<HTMLButtonElement>('resetAviDefaultsBtn'),
  gifLoopModeSelect: getRequiredElement<HTMLSelectElement>('gifLoopModeSelect'),
  gifBestQualityFps: getRequiredElement<HTMLInputElement>('gifBestQualityFps'),
  gifBestQualityMaxDimension: getRequiredElement<HTMLInputElement>('gifBestQualityMaxDimension'),
  gifBestQualityMaxColors: getRequiredElement<HTMLInputElement>('gifBestQualityMaxColors'),
  gifBestQualityDither: getRequiredElement<HTMLSelectElement>('gifBestQualityDither'),
  gifQualityFps: getRequiredElement<HTMLInputElement>('gifQualityFps'),
  gifQualityMaxDimension: getRequiredElement<HTMLInputElement>('gifQualityMaxDimension'),
  gifQualityMaxColors: getRequiredElement<HTMLInputElement>('gifQualityMaxColors'),
  gifQualityDither: getRequiredElement<HTMLSelectElement>('gifQualityDither'),
  gifBalancedFps: getRequiredElement<HTMLInputElement>('gifBalancedFps'),
  gifBalancedMaxDimension: getRequiredElement<HTMLInputElement>('gifBalancedMaxDimension'),
  gifBalancedMaxColors: getRequiredElement<HTMLInputElement>('gifBalancedMaxColors'),
  gifBalancedDither: getRequiredElement<HTMLSelectElement>('gifBalancedDither'),
  gifBestCompressionFps: getRequiredElement<HTMLInputElement>('gifBestCompressionFps'),
  gifBestCompressionMaxDimension: getRequiredElement<HTMLInputElement>(
    'gifBestCompressionMaxDimension'
  ),
  gifBestCompressionMaxColors: getRequiredElement<HTMLInputElement>('gifBestCompressionMaxColors'),
  gifBestCompressionDither: getRequiredElement<HTMLSelectElement>('gifBestCompressionDither'),
  closeSettings: getRequiredElement<HTMLButtonElement>('closeSettings'),
  outputDirBtn: getRequiredElement<HTMLButtonElement>('outputDirBtn'),
  outputDirResetBtn: getRequiredElement<HTMLButtonElement>('outputDirResetBtn'),
  outputPath: getRequiredElement<HTMLSpanElement>('outputPath'),
  themeSelect: getRequiredElement<HTMLSelectElement>('themeSelect'),
  themeSwitcher: getRequiredElement<HTMLDivElement>('themeSwitcher'),
  customThemeRow: getRequiredElement<HTMLDivElement>('customThemeRow'),
  customThemeGallery: getRequiredElement<HTMLDivElement>('customThemeGallery'),
  uiStyleSwitcher: getRequiredElement<HTMLDivElement>('uiStyleSwitcher'),
  resetSettingsBtn: getRequiredElement<HTMLButtonElement>('resetSettingsBtn'),
  checkUpdateBtn: getRequiredElement<HTMLButtonElement>('checkUpdateBtn'),
  updateBadge: getRequiredElement<HTMLSpanElement>('updateBadge'),
  autoCheckUpdatesCheck: getRequiredElement<HTMLInputElement>('autoCheckUpdatesCheck'),
  updateChannelSelect: getRequiredElement<HTMLSelectElement>('updateChannelSelect'),
  versionInfo: getRequiredElement<HTMLSpanElement>('versionInfo'),
  versionLink: getRequiredElement<HTMLAnchorElement>('versionLink'),
  ffmpegWarning: getRequiredElement<HTMLDivElement>('ffmpegWarning'),
  dynamicModal: getRequiredElement<HTMLDivElement>('dynamicModal'),
  viewCreditsBtn: getRequiredElement<HTMLButtonElement>('viewCreditsBtn'),
  creditsModal: getRequiredElement<HTMLDivElement>('creditsModal'),
  closeCredits: getRequiredElement<HTMLButtonElement>('closeCredits'),
  licensesList: getRequiredElement<HTMLDivElement>('licensesList'),
  debugOutputCheck: getRequiredElement<HTMLInputElement>('debugOutputCheck'),
  advancedPresetsCheck: getRequiredElement<HTMLInputElement>('advancedPresetsCheck'),
  removeSpacesCheck: getRequiredElement<HTMLInputElement>('removeSpacesCheck'),
  useSystemFFmpegCheck: getRequiredElement<HTMLInputElement>('useSystemFFmpegCheck'),
  useCpuDecodingWhenGpuCheck: getRequiredElement<HTMLInputElement>('useCpuDecodingWhenGpuCheck'),
  moveOriginalToTrashOnSuccessCheck: getRequiredElement<HTMLInputElement>(
    'moveOriginalToTrashOnSuccessCheck'
  ),
  trashOriginalNotice: getRequiredElement<HTMLParagraphElement>('trashOriginalNotice'),
  notifyOnConversionCompleteCheck: getRequiredElement<HTMLInputElement>(
    'notifyOnConversionCompleteCheck'
  ),
  preventSleepWhileConvertingCheck: getRequiredElement<HTMLInputElement>(
    'preventSleepWhileConvertingCheck'
  ),
  showLogsBtn: getRequiredElement<HTMLButtonElement>('showLogsBtn'),
  logsModal: getRequiredElement<HTMLDivElement>('logsModal'),
  closeLogs: getRequiredElement<HTMLButtonElement>('closeLogs'),
  logsContent: getRequiredElement<HTMLPreElement>('logsContent'),
  clearLogsBtn: getRequiredElement<HTMLButtonElement>('clearLogsBtn'),
  copyLogsBtn: getRequiredElement<HTMLButtonElement>('copyLogsBtn'),
  statusDetailsBtn: getRequiredElement<HTMLButtonElement>('statusDetailsBtn'),
  errorDetailsModal: getRequiredElement<HTMLDivElement>('errorDetailsModal'),
  errorDetailsTitle: getRequiredElement<HTMLHeadingElement>('errorDetailsTitle'),
  errorDetailsSummary: getRequiredElement<HTMLParagraphElement>('errorDetailsSummary'),
  errorDetailsContent: getRequiredElement<HTMLPreElement>('errorDetailsContent'),
  closeErrorDetails: getRequiredElement<HTMLButtonElement>('closeErrorDetails'),
  copyErrorDetailsBtn: getRequiredElement<HTMLButtonElement>('copyErrorDetailsBtn'),
};
